# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a22965b0a0a6979683ba798e655eb7bcddb4b4de361beb3654ba816b5652c307a00031d1d4b4cf52921e63ff0ab77f20ee3eb46533d867e44348f1450882b5f

test:
  secret_key_base: 895cad7742a5c7199206455a0e0fb42f265a7f67e11787bc3a77139efa00f36dc753630538962bfbff740f30440298717372ad56fb4041755400ff72cc9eaaf3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
